services:
  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:v5.10
    restart: always
    command: -r -u -w
    ports:
      - '8100:8100'
    volumes:
      - './config:/app/config'
      - './worlds:/app/worlds'
      - './data:/app/data'
      - './web:/app/web'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:lts
    restart: always
    env_file:
      - .env
    volumes:
      - './db_data:/var/lib/mysql'
    healthcheck:                     # ← tells Compose when MySQL is ready
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -uroot -p$${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 5s
      retries: 10
      timeout: 3s
  php:
    # image: php:8.4-fpm-alpine
    build:
      dockerfile: php-dockerfile
      context: .
    restart: always
    volumes:
      - './web:/var/www/html'
      # - './php:/usr/src/php'
    depends_on:
      db:
        condition: service_healthy
  webserver:
    image: nginx:stable-alpine
    restart: always
    ports:
      - '8180:80'
    volumes:
      - './web:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - db
      - php