services:
  bluemap:  # You can comment this entire service out if not needed
    image: ghcr.io/bluemap-minecraft/bluemap:v5.10
    restart: always
    command: -r -u -w
    ports:
      - '8100:8100'
    volumes:
      - './config:/app/config'
      - './worlds:/app/worlds'
      - './data:/app/data'
      - './web:/app/web'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:lts
    restart: always
    env_file:
      - .env
    volumes:
      - './db_data:/var/lib/mysql'
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost --user=root --password=${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Allows time for initialization scripts to run
  php:
    build:
      dockerfile: php-dockerfile
      context: .
    restart: always
    volumes:
      - './web:/var/www/html'
    depends_on:
      db:
        condition: service_healthy
  webserver:
    image: nginx:stable-alpine
    restart: always
    ports:
      - '8180:80'
    volumes:
      - './web:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - db
      - php